from __future__ import annotations

import fnmatch
import hashlib
import re
from collections.abc import Callable
from pathlib import Path

IGNORE_DIRS = {
    ".storage",
    ".cloud",
    ".cache",
    ".venv",
    ".vscode",
    ".idea",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    "tts",
    "__pycache__",
    ".git",
    "hacs_frontend",
    "node_modules",
}

# Credential-bearing directories. Excluded by default and reached only by the
# Override mode — unlike runtime artifacts, which no mode can re-enable.
SECURITY_DIRS = {
    ".ssh",
}

# Runtime artifacts are never synced, and no mode can re-enable them: this add
# on is a configuration sync tool, not a backup solution, so a Git copy of a
# database or a log has no restore value. They are write-heavy, instance-tied
# or regenerated by Home Assistant, and only add churn (or corruption risk) to
# the repository.
RUNTIME_PATTERNS = (
    "home-assistant.log",
    "home-assistant.log.*",
    "home-assistant_v2.db",
    "home-assistant_v2.db-*",
    ".ha_run.lock",
    ".ruff.toml",
    "*.db",
    "*.db-*",
    "*.sqlite",
    "*.sqlite3",
    "*.wal",
    "*.shm",
    "*.tmp",
    "*.swp",
    "*.pyc",
    "*.log",
    "*.js.map",
    ".yaml_fix_backups",
    ".yaml_fix_backups/*",
    ".ha_fix_yaml.py",
    ".smbdelete*",
    ".DS_Store",
    "Thumbs.db",
    "core.config_entries",
)

# Credential-bearing files are excluded by default and are only synced when the
# user explicitly opts into the security override (danger zone).
SECURITY_PATTERNS = (
    "secrets.yaml",
    "ip_bans.yaml",
    "known_devices.yaml",
    ".env",
    "*.pem",
    "*.key",
    "*.crt",
    "*.cer",
    "*.der",
    "*.p12",
    "*.pfx",
    "*.p8",
    "*.pub",
    "*.asc",
    "id_rsa",
    "id_rsa.pub",
    "id_dsa",
    "id_dsa.pub",
    "id_ecdsa",
    "id_ecdsa.pub",
    "id_ed25519",
    "id_ed25519.pub",
)

# Combined view of everything excluded by default. Retained for callers and
# tests that report on the full ignore set.
IGNORE_PATTERNS = RUNTIME_PATTERNS + SECURITY_PATTERNS

# Upper bound on user-supplied allowlist entries, to keep a malformed options
# payload from turning every sync into a pathological pattern match.
MAX_SAFE_CONFIG_PATHS = 100

SENSITIVE_PATTERNS = (
    ".storage/",
    "secrets.yaml",
    "secret",
)
SENSITIVE_NAME_PATTERNS = (
    re.compile(r"(password|passwd|secret|token|credential|private|api[_-]?key|oauth|cookie|session)", re.I),
)
SENSITIVE_CONTENT_PATTERNS = (
    re.compile(r"(?i)\b(password|passwd|secret|token|api[_-]?key|client_secret)\b\s*[:=]"),
    re.compile(r"(?i)\bbearer\s+[A-Za-z0-9._\-]{20,}"),
    re.compile(r"(?i)\bsk-[A-Za-z0-9]{20,}"),
)

MAX_CONTENT_SCAN_BYTES = 2 * 1024 * 1024

# Largest file a sync will try to upload. GitHub's contents API rejects
# anything this size outright ("Sorry, the file is too large to be processed")
# and base64-encodes the payload on the way, making it a third larger again.
# Nothing in a configuration directory legitimately reaches this - the biggest
# real offender seen was a 286 MB archive another add-on had written into the
# config root - so the cap costs nothing and turns a total run failure into a
# reported skip.
MAX_SYNCABLE_BYTES = 50 * 1024 * 1024


class GitIgnoreMatcher:
    """Match repo-relative paths against a .gitignore file's patterns.

    Implements common gitignore semantics: comments, blank lines, ``!``
    negation, trailing-``/`` directory patterns, anchored patterns (contain a
    ``/``), and basename patterns. Patterns are matched case-sensitively; an
    anchored pattern that names a directory also covers everything beneath it.
    Last matching rule wins; a path with no matching rule is kept.
    """

    def __init__(self) -> None:
        self._rules: list[tuple[bool, bool, str]] = []
        self._has_rules = False

    @property
    def has_rules(self) -> bool:
        return self._has_rules

    @classmethod
    def from_file(cls, path: Path) -> GitIgnoreMatcher:
        matcher = cls()
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            return matcher
        matcher.add_text(text)
        return matcher

    def add_text(self, text: str) -> None:
        for raw in text.splitlines():
            line = raw.rstrip().lstrip()
            if not line or line.startswith("#"):
                continue
            negate = line.startswith("!")
            if negate:
                line = line[1:].lstrip()
            dir_only = line.endswith("/")
            pattern = line[:-1] if dir_only else line
            if not pattern:
                continue
            pattern = pattern.replace("\\", "/").lstrip("/")
            if not pattern:
                continue
            self._rules.append((negate, dir_only, pattern))
            self._has_rules = True

    def match(self, relative: str) -> bool:
        """Return True if the repo-relative path should be ignored."""
        if not self._has_rules:
            return False
        relative = (relative or "").replace("\\", "/")
        while relative.startswith("./"):
            relative = relative[2:]
        if not relative:
            return False
        ignored = False
        for negate, dir_only, pattern in self._rules:
            if _gitignore_rule_matches(relative, dir_only, pattern):
                ignored = not negate
        return ignored


def _gitignore_rule_matches(relative: str, dir_only: bool, pattern: str) -> bool:
    if "/" in pattern:
        if fnmatch.fnmatchcase(relative, pattern):
            return True
        if dir_only:
            return relative.startswith(pattern + "/")
        return False
    return any(fnmatch.fnmatchcase(part, pattern) for part in relative.split("/"))



def _is_runtime_artifact(relative_path: str) -> bool:
    """Runtime/ephemeral artifacts. Always excluded, override cannot re-enable."""
    normalized = relative_path.replace("\\", "/").lower()
    if any(part.lower() in IGNORE_DIRS for part in Path(relative_path).parts):
        return True
    return any(fnmatch.fnmatchcase(normalized, pattern) for pattern in RUNTIME_PATTERNS)


def _is_security_excluded(relative_path: str) -> bool:
    """Credential-bearing paths. Excluded unless the security override is on."""
    normalized = relative_path.replace("\\", "/").lower()
    parts = Path(relative_path).parts
    if any(part.lower() in SECURITY_DIRS for part in parts):
        return True
    if any(pattern in normalized for pattern in SENSITIVE_PATTERNS):
        return True
    return any(fnmatch.fnmatchcase(normalized, pattern) for pattern in SECURITY_PATTERNS)


def is_ignored(
    relative_path: str,
    override: bool = False,
) -> bool:
    """Decide whether a repo-relative path is excluded from the sync.

    Precedence, highest first:

    1. Runtime artifacts - always excluded; no mode re-enables these.
    2. Security patterns - excluded unless ``override``.
    3. Name/content heuristics - excluded unless ``override``.

    Selection is deliberately not a concern here: the engine decides which
    paths are in scope, and the security checks then run on whatever survives.
    """
    if _is_runtime_artifact(relative_path):
        return True
    if _is_security_excluded(relative_path):
        return not override
    if override:
        return False
    return is_sensitive_candidate(relative_path)


def is_sensitive_candidate(relative_path: str) -> bool:
    normalized = relative_path.replace("\\", "/")
    name = Path(relative_path).name
    return any(pattern.search(normalized) or pattern.search(name) for pattern in SENSITIVE_NAME_PATTERNS)


def _file_contains_sensitive_content(path: Path) -> bool:
    try:
        with path.open("rb") as handle:
            sample = handle.read(MAX_CONTENT_SCAN_BYTES)
    except OSError:
        return False
    text = sample.decode("utf-8", errors="ignore")
    return any(pattern.search(text) for pattern in SENSITIVE_CONTENT_PATTERNS)


def scan_sensitive_files(
    root: Path,
    override: bool = False,
    in_scope: Callable[[str], bool] | None = None,
) -> list[str]:
    """List files held back by the security checks.

    ``in_scope`` restricts the report to files the user actually selected, so
    the warning describes what was blocked rather than everything on disk that
    happens to look sensitive.
    """
    if override or not root.exists():
        return []
    flagged: list[str] = []
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        relative = path.relative_to(root).as_posix()
        if in_scope is not None and not in_scope(relative):
            continue
        if _is_runtime_artifact(relative) or _is_security_excluded(relative):
            continue
        reasons = []
        if is_sensitive_candidate(relative):
            reasons.append("name")
        if _file_contains_sensitive_content(path):
            reasons.append("content")
        if reasons:
            flagged.append(relative)
    return sorted(set(flagged))


def _is_file_sensitive(
    root: Path,
    path: Path,
    override: bool = False,
) -> bool:
    """Check if a file should be excluded from upload.

    ``is_ignored`` evaluates the runtime floor first, so no mode can reach it.
    A path that survives it is then subject to the security checks, which
    ``override`` bypasses for both the pattern list and the content scan.
    """
    if is_ignored(path.relative_to(root).as_posix(), override=override):
        return True
    return _file_contains_sensitive_content(path) if not override else False


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while True:
            chunk = handle.read(1024 * 1024)
            if not chunk:
                break
            digest.update(chunk)
    return digest.hexdigest()


def _file_size(path: Path) -> int:
    """Size in bytes, or 0 if the file cannot be stat'ed.

    A file that disappears mid-walk is not a reason to abort the scan; the
    read that follows will fail on its own if it is somehow still there.
    """
    try:
        return path.stat().st_size
    except OSError:
        return 0


def build_hash_index(
    root: Path,
    override: bool = False,
    oversized: list[str] | None = None,
) -> dict[str, str]:
    """Digest every syncable file under ``root``, keyed by relative path.

    Pass ``oversized`` to collect the paths skipped for being too large to
    upload. It is optional because the walk already knows which files those
    are, and a second walk to find them again would be pure cost.
    """
    if not root.exists():
        return {}

    index: dict[str, str] = {}
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        relative = path.relative_to(root).as_posix()
        if _file_size(path) > MAX_SYNCABLE_BYTES:
            # Skipped rather than attempted. GitHub answers with a 422 for a
            # file this size, and that error used to abort the whole run, so a
            # single archive dropped in the config directory cost the user
            # every other file too. Skipping it also avoids hashing hundreds
            # of megabytes to find out nothing can be done with the digest.
            if oversized is not None:
                oversized.append(relative)
            continue
        if _is_file_sensitive(root, path, override=override):
            continue
        index[relative] = sha256_file(path)
    return index


def diff_hash_indexes(previous: dict[str, str], current: dict[str, str]) -> tuple[list[str], list[str], list[str]]:
    previous_keys = set(previous)
    current_keys = set(current)

    added = sorted(current_keys - previous_keys)
    removed = sorted(previous_keys - current_keys)
    changed = sorted(
        key for key in (current_keys & previous_keys) if previous.get(key) != current.get(key)
    )
    return added, changed, removed
