from __future__ import annotations

import fnmatch
import hashlib
import re
from pathlib import Path
from typing import Sequence

IGNORE_DIRS = {
    ".storage",
    ".cloud",
    ".cache",
    ".venv",
    ".vscode",
    ".idea",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    "tts",
    "__pycache__",
    ".git",
    "hacs_frontend",
    "node_modules",
    ".ssh",
}
# Runtime artifacts are never synced, and cannot be re-enabled by either the
# security override or a safe-path allowlist entry. They are write-heavy,
# instance-tied or regenerated by Home Assistant, so a Git copy has no restore
# value and only adds churn (or corruption risk) to the repository.
RUNTIME_PATTERNS = (
    "home-assistant.log",
    "home-assistant.log.*",
    "home-assistant_v2.db",
    "home-assistant_v2.db-*",
    ".ha_run.lock",
    ".ruff.toml",
    "*.db",
    "*.db-*",
    "*.sqlite",
    "*.sqlite3",
    "*.wal",
    "*.shm",
    "*.tmp",
    "*.swp",
    "*.pyc",
    "*.log",
    "*.js.map",
    ".yaml_fix_backups",
    ".yaml_fix_backups/*",
    ".ha_fix_yaml.py",
    ".smbdelete*",
    ".DS_Store",
    "Thumbs.db",
    "core.config_entries",
)

# Credential-bearing files are excluded by default and are only synced when the
# user explicitly opts into the security override (danger zone).
SECURITY_PATTERNS = (
    "secrets.yaml",
    "ip_bans.yaml",
    "known_devices.yaml",
    ".env",
    "*.pem",
    "*.key",
    "*.crt",
    "*.cer",
    "*.der",
    "*.p12",
    "*.pfx",
    "*.p8",
    "*.pub",
    "*.asc",
    "id_rsa",
    "id_rsa.pub",
    "id_dsa",
    "id_dsa.pub",
    "id_ecdsa",
    "id_ecdsa.pub",
    "id_ed25519",
    "id_ed25519.pub",
)

# Combined view of everything excluded by default. Retained for callers and
# tests that report on the full ignore set.
IGNORE_PATTERNS = RUNTIME_PATTERNS + SECURITY_PATTERNS

# Built-in safe config paths. These are configuration, not runtime state, and
# are commonly expected to contain credentials (ESPHome and Zigbee2MQTT both
# embed wifi passwords and API keys inline).
SAFE_CONFIG_PATHS = (
    "esphome/*.yaml",
    "zigbee2mqtt/*.yaml",
)

# Upper bound on user-supplied allowlist entries, to keep a malformed options
# payload from turning every sync into a pathological pattern match.
MAX_SAFE_CONFIG_PATHS = 100

SENSITIVE_PATTERNS = (
    ".storage/",
    "secrets.yaml",
    "secret",
)
SENSITIVE_NAME_PATTERNS = (
    re.compile(r"(password|passwd|secret|token|credential|private|api[_-]?key|oauth|cookie|session)", re.I),
)
SENSITIVE_CONTENT_PATTERNS = (
    re.compile(r"(?i)\b(password|passwd|secret|token|api[_-]?key|client_secret)\b\s*[:=]"),
    re.compile(r"(?i)\bbearer\s+[A-Za-z0-9._\-]{20,}"),
    re.compile(r"(?i)\bsk-[A-Za-z0-9]{20,}"),
)

MAX_CONTENT_SCAN_BYTES = 2 * 1024 * 1024


class GitIgnoreMatcher:
    """Match repo-relative paths against a .gitignore file's patterns.

    Implements common gitignore semantics: comments, blank lines, ``!``
    negation, trailing-``/`` directory patterns, anchored patterns (contain a
    ``/``), and basename patterns. Patterns are matched case-sensitively; an
    anchored pattern that names a directory also covers everything beneath it.
    Last matching rule wins; a path with no matching rule is kept.
    """

    def __init__(self) -> None:
        self._rules: list[tuple[bool, bool, str]] = []
        self._has_rules = False

    @property
    def has_rules(self) -> bool:
        return self._has_rules

    @classmethod
    def from_file(cls, path: Path) -> GitIgnoreMatcher:
        matcher = cls()
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            return matcher
        matcher.add_text(text)
        return matcher

    def add_text(self, text: str) -> None:
        for raw in text.splitlines():
            line = raw.rstrip().lstrip()
            if not line or line.startswith("#"):
                continue
            negate = line.startswith("!")
            if negate:
                line = line[1:].lstrip()
            dir_only = line.endswith("/")
            pattern = line[:-1] if dir_only else line
            if not pattern:
                continue
            pattern = pattern.replace("\\", "/").lstrip("/")
            if not pattern:
                continue
            self._rules.append((negate, dir_only, pattern))
            self._has_rules = True

    def match(self, relative: str) -> bool:
        """Return True if the repo-relative path should be ignored."""
        if not self._has_rules:
            return False
        relative = (relative or "").replace("\\", "/")
        while relative.startswith("./"):
            relative = relative[2:]
        if not relative:
            return False
        ignored = False
        for negate, dir_only, pattern in self._rules:
            if _gitignore_rule_matches(relative, dir_only, pattern):
                ignored = not negate
        return ignored


def _gitignore_rule_matches(relative: str, dir_only: bool, pattern: str) -> bool:
    if "/" in pattern:
        if fnmatch.fnmatchcase(relative, pattern):
            return True
        if dir_only:
            return relative.startswith(pattern + "/")
        return False
    return any(fnmatch.fnmatchcase(part, pattern) for part in relative.split("/"))



def _safe_config_patterns(safe_paths: Sequence[str] | None = None) -> tuple[str, ...]:
    """Built-in safe config paths plus any user-supplied extras."""
    if not safe_paths:
        return SAFE_CONFIG_PATHS
    return SAFE_CONFIG_PATHS + tuple(str(pattern) for pattern in safe_paths)


def _is_safe_config_path(relative_path: str, safe_paths: Sequence[str] | None = None) -> bool:
    normalized = relative_path.replace("\\", "/")
    lowered = normalized.lower()
    for pattern in _safe_config_patterns(safe_paths):
        if fnmatch.fnmatchcase(normalized, pattern) or fnmatch.fnmatchcase(lowered, pattern.lower()):
            return True
    return False


def _is_runtime_artifact(relative_path: str) -> bool:
    """Runtime/ephemeral artifacts. Always excluded, override cannot re-enable."""
    normalized = relative_path.replace("\\", "/").lower()
    if any(part.lower() in IGNORE_DIRS for part in Path(relative_path).parts):
        return True
    return any(fnmatch.fnmatchcase(normalized, pattern) for pattern in RUNTIME_PATTERNS)


def _is_security_excluded(relative_path: str) -> bool:
    """Credential-bearing paths. Excluded unless the security override is on."""
    normalized = relative_path.replace("\\", "/").lower()
    if any(pattern in normalized for pattern in SENSITIVE_PATTERNS):
        return True
    return any(fnmatch.fnmatchcase(normalized, pattern) for pattern in SECURITY_PATTERNS)


def is_ignored(
    relative_path: str,
    override: bool = False,
    safe_paths: Sequence[str] | None = None,
) -> bool:
    """Decide whether a repo-relative path is excluded from the sync.

    Precedence, highest first:

    1. Runtime artifacts - always excluded.
    2. Safe config paths - never excluded (built-in plus user allowlist).
    3. Security patterns - excluded unless ``override``.
    4. Name/content heuristics - excluded unless ``override``.
    """
    if _is_runtime_artifact(relative_path):
        return True
    if _is_safe_config_path(relative_path, safe_paths):
        return False
    if _is_security_excluded(relative_path):
        return not override
    if override:
        return False
    return is_sensitive_candidate(relative_path)


def is_sensitive_candidate(relative_path: str) -> bool:
    normalized = relative_path.replace("\\", "/")
    name = Path(relative_path).name
    return any(pattern.search(normalized) or pattern.search(name) for pattern in SENSITIVE_NAME_PATTERNS)


def _file_contains_sensitive_content(path: Path) -> bool:
    try:
        with path.open("rb") as handle:
            sample = handle.read(MAX_CONTENT_SCAN_BYTES)
    except OSError:
        return False
    text = sample.decode("utf-8", errors="ignore")
    return any(pattern.search(text) for pattern in SENSITIVE_CONTENT_PATTERNS)


def scan_sensitive_files(
    root: Path,
    override: bool = False,
    safe_paths: Sequence[str] | None = None,
) -> list[str]:
    if override or not root.exists():
        return []
    flagged: list[str] = []
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        relative = path.relative_to(root).as_posix()
        if _is_runtime_artifact(relative) or _is_security_excluded(relative):
            continue
        if _is_safe_config_path(relative, safe_paths):
            continue
        reasons = []
        if is_sensitive_candidate(relative):
            reasons.append("name")
        if _file_contains_sensitive_content(path):
            reasons.append("content")
        if reasons:
            flagged.append(relative)
    return sorted(set(flagged))


def _is_file_sensitive(
    root: Path,
    path: Path,
    override: bool = False,
    safe_paths: Sequence[str] | None = None,
) -> bool:
    """Check if a file should be excluded from upload.

    Safe config paths short-circuit before the content scan. This matters:
    ESPHome and Zigbee2MQTT configs embed ``password:``/``api_key:`` inline, so
    without this an allowlisted file would still be dropped by the content scan.
    """
    relative = path.relative_to(root).as_posix()
    if _is_runtime_artifact(relative):
        return True
    if _is_safe_config_path(relative, safe_paths):
        return False
    if is_ignored(relative, override=override, safe_paths=safe_paths):
        return True
    return _file_contains_sensitive_content(path) if not override else False


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while True:
            chunk = handle.read(1024 * 1024)
            if not chunk:
                break
            digest.update(chunk)
    return digest.hexdigest()


def build_hash_index(
    root: Path,
    override: bool = False,
    safe_paths: Sequence[str] | None = None,
) -> dict[str, str]:
    if not root.exists():
        return {}

    index: dict[str, str] = {}
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        relative = path.relative_to(root).as_posix()
        if _is_file_sensitive(root, path, override=override, safe_paths=safe_paths):
            continue
        index[relative] = sha256_file(path)
    return index


def diff_hash_indexes(previous: dict[str, str], current: dict[str, str]) -> tuple[list[str], list[str], list[str]]:
    previous_keys = set(previous)
    current_keys = set(current)

    added = sorted(current_keys - previous_keys)
    removed = sorted(previous_keys - current_keys)
    changed = sorted(
        key for key in (current_keys & previous_keys) if previous.get(key) != current.get(key)
    )
    return added, changed, removed
